name       : dotconf
version    : 1.3
release    : 2
source     :
    - https://github.com/williamh/dotconf/archive/v1.3.tar.gz : 7f1ecf40de1ad002a065a321582ed34f8c14242309c3547ad59710ae3c805653
license    : LGPL-2.1
component  : programming.library
summary    : Dot file config parser
description: |
    Dot file config parser
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
